language: scala

os:
  - linux
  - osx

osx_image: 
  - xcode8

scala:
  - "2.13.1"
  - "2.12.10"
  - "2.11.12"

jdk:
  - openjdk12
  - openjdk11
  - openjdk10
  - openjdk9
  - openjdk8

sudo: false

notifications:
  email:
    recipients:
      - marko.elezovic@oradian.com

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
